server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlite:hotel.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "hyper-secret-key-must-be-at-least-32-bytes!"
  expiration: 3600000
